# Generated by Django 4.0.1 on 2022-02-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mychart',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mychart',
            old_name='date',
            new_name='rank',
        ),
    ]
