# Generated by Django 4.0.1 on 2022-02-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_rename_label_mychart_name_rename_date_mychart_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='volume_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
