# Generated by Django 4.0.1 on 2022-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_volume_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume_table',
            name='total_volumeRls',
            field=models.IntegerField(null=True),
        ),
    ]
