# Generated by Django 4.0.1 on 2022-02-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_volume_table_total_volumerls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='volume_table',
        ),
    ]
