# Generated by Django 4.0.1 on 2022-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_delete_volume_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeTable',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('total_volumerls', models.IntegerField(blank=True, db_column='total_volumeRls', null=True)),
                ('total_volumeusdt', models.IntegerField(blank=True, db_column='total_volumeUsdt', null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'volume_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
