# Generated by Django 4.0.1 on 2022-02-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0011_voldatabase_delete_volumetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mychart',
        ),
        migrations.DeleteModel(
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='VolDatabase',
        ),
    ]
