# Generated by Django 4.0.1 on 2022-02-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0012_delete_mychart_delete_timestamp_delete_voldatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='mychart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
