# Generated by Django 4.0.1 on 2022-02-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0013_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolDatabase',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('total_volumerls', models.IntegerField(blank=True, db_column='total_volumeRls', null=True)),
                ('total_volumeusdt', models.IntegerField(blank=True, db_column='total_volumeUsdt', null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_at_int_timestamp', models.IntegerField(blank=True, null=True)),
                ('created_at_int_datetime', models.IntegerField(blank=True, null=True)),
                ('created_at_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'volume_table',
                'managed': False,
            },
        ),
    ]
