# Generated by Django 4.0.1 on 2022-02-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0014_voldatabase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='voldatabase',
            table='vol_database',
        ),
    ]
